spring:
  application:
    name: msvc-test

  datasource:
    url: jdbc:postgresql://localhost:5432/bd_test
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # validate hace que Hibernate valide el esquema de la base de datos en función de las entidades mapeadas. Si el esquema no coincide, se lanzará una excepción. -> usar siempre eso para evitar que Hibernate realice cambios automáticos en la base de datos, lo que puede ser peligroso en entornos de producción.

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 20d185d2ddb3ba
    password: 8e6499ab6c7ba3
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    disable-swagger-default-url: true
    operationsSorter: method

frontend:
  urlTest: http://localhost:5173

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

