spring:
  application:
    name: msvc-test

  datasource:
    url: jdbc:postgresql://localhost:5432/bd_test
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    disable-swagger-default-url: true
    operationsSorter: method

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

